Repository Pet-MatchMaker-2412/pet_matchmaker_be, pull requests merged in 2025-04, with the labels that each got.

#14 Chore: Add, install, and configure required gems
  .rspec
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/.keep
  config/environments/test.rb
  config/initializers/cors.rb
  lib/tasks/factory_bot.rake
  spec/rails_helper.rb
  spec/requests/api/v1/.keep
  spec/spec_helper.rb
Labels: backend

#17 Feature: Add questions, answers, animals, and weights to seeds
  app/models/recommended_animals_weight.rb
  db/migrate/20250419010907_create_recommended_animals.rb
  db/schema.rb
  db/seeds.rb
  docs/questionnaire_and_probabilities.md
  spec/models/recommended_animals_weight_spec.rb
Labels: backend, enhancement, Sprint 1

#19 Feature: Create User Endpoint
  app/controllers/api/v1/.keep
  app/controllers/api/v1/users_controller.rb
  app/poros/error_message.rb
  app/serializers/error_serializer.rb
  app/serializers/user_serializer.rb
  config/routes.rb
  docs/json_contracts.md
  spec/requests/api/v1/.keep
  spec/requests/api/v1/users_request_spec.rb
Labels: backend, enhancement, Sprint 1

#21 Get Questions endpoint
  app/controllers/api/v1/questions_controller.rb
  app/models/answer.rb
  app/models/question.rb
  app/serializers/answer_serializer.rb
  app/serializers/question_serializer.rb
  config/routes.rb
  docs/json_contracts.md
  spec/models/answer_spec.rb
  spec/models/question_spec.rb
  spec/requests/api/v1/questions_request_spec.rb
Labels: backend, Sprint 1

#20 Feature: Get Petfinder Animals Endpoint w/ Mock Data
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/petfinder_animals_controller.rb
  app/poros/petfinder_animal.rb
  app/serializers/petfinder_animal_serializer.rb
  config/environments/test.rb
  config/routes.rb
  docs/json_contracts.md
  spec/factories/recommended_animals.rb
  spec/fixtures/petfinder_animals.json
  spec/requests/api/v1/petfinder_animals_request_spec.rb
Labels: backend, enhancement, Sprint 1

#27 Add Columns to Recommended Animals for PetFinder Query
  app/models/recommended_animal.rb
  db/migrate/20250419010907_create_recommended_animals.rb
  db/schema.rb
  db/seeds.rb
  spec/models/recommended_animal_spec.rb
Labels: backend, question, Sprint 2

#26 Fix: Rework Questionnaire Submission Serializer
  Gemfile.lock
  app/controllers/api/v1/petfinder_animals_controller.rb
  app/controllers/api/v1/questionnaire_submissions_controller.rb
  app/controllers/application_controller.rb
  app/serializers/questionnaire_submission_serializer.rb
  app/serializers/questionnaire_submissions_serializer.rb
  app/serializers/recommended_animal_serializer.rb
  app/serializers/submission_answer_serializer.rb
  config/credentials.yml.enc
  docs/json_contracts.md
  spec/factories/recommended_animals.rb
  spec/rails_helper.rb
  spec/requests/api/v1/petfinder_animals_request_spec.rb
  spec/requests/api/v1/questionnaire_submissions_request_spec.rb
Labels: backend, Sprint 1

#30 Feature: Post Questionnaire Submission Endpoint
  app/controllers/api/v1/questionnaire_submissions_controller.rb
  app/controllers/application_controller.rb
  app/models/questionnaire_submission.rb
  config/routes.rb
  spec/models/questionnaire_submission_spec.rb
  spec/requests/api/v1/questionnaire_submissions_request_spec.rb
Labels: backend, enhancement, Sprint 2

#33 Feature: Save Questionnaire Submission Endpoint
  app/controllers/api/v1/questionnaire_submissions_controller.rb
  config/routes.rb
  spec/requests/api/v1/questionnaire_submissions_request_spec.rb
Labels: backend, enhancement, Sprint 2

#36 Feature: The Big Kahuna
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/questionnaire_submissions_controller.rb
  app/models/recommended_animal.rb
  spec/models/recommended_animal_spec.rb
  spec/requests/api/v1/questionnaire_submissions_request_spec.rb
Labels: backend, enhancement, Sprint 2

#39 Seed mock user with realistic questionnaire-submission and answers
  db/seeds.rb
Labels: backend, Sprint 2

#41 Will Small Refactor
  app/controllers/api/v1/questionnaire_submissions_controller.rb
  app/serializers/recommended_animal_serializer.rb
Labels: backend

#42 Add 'Leopard Gecko' photo_url to seeds.rb
  db/seeds.rb
  docs/json_contracts.md
Labels: backend
